### ISSUE TITLE
Build-name ignored for wails build output

### ISSUE THREAD

**Issue by olup** [dAppServer/wails-build-action#1]
`build-name` is not passed to wails build command, binary name is then always the project name, and following operations on the binary based on build-name are then failing.

**Comment by Snider** [comment]
Oops, thank you for fixing my mistake... my brain had reached a stopping point.

**Comment by olup** [comment]
No, thanks for this very helpful action. How can I reference this update ? Do you need to push a release ?

**Comment by olup** [comment]
I referenced main and it's fine

**Comment by olup** [comment]
https://github.com/dAppServer/wails-build-action/pull/3/files There was a dollar sign missing in my PR, this needs a fix asap...
